package main

import (
	"fmt"
	"io"
	"os"
)

var (
	files = map[string]string{
		"mainTemplate": "template.html",
	}
	outFile = "template_autogenerated.go"
)

// Read all files and save them as strings literals in wordlists.go
func main() {
	out, err := os.Create(outFile)
	if err != nil {
		fmt.Println(err)
	}
	defer out.Close()

	out.Write([]byte("package main\n\nconst (\n"))

	for k, v := range files {
		out.Write([]byte(k + " = `"))
		f, err := os.Open(v)
		if err != nil {
			fmt.Println(err)
		}
		defer f.Close()
		io.Copy(out, f)
		out.Write([]byte("`\n"))
	}
	out.Write([]byte(")\n"))
}
