// Copyright 2016-2021, Lenses.io Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"fmt"
	"io"
	"os"
)

var (
	files = map[string]string{
		"mainTemplate": "template.html",
	}
	outFile = "template_autogenerated.go"
)

// Read all files and save them as strings literals in wordlists.go
func main() {
	out, err := os.Create(outFile)
	if err != nil {
		fmt.Println(err)
	}
	defer out.Close()

	out.Write([]byte("package main\n\nconst (\n"))

	for k, v := range files {
		out.Write([]byte(k + " = `"))
		f, err := os.Open(v)
		if err != nil {
			fmt.Println(err)
		}
		defer f.Close()
		io.Copy(out, f)
		out.Write([]byte("`\n"))
	}
	out.Write([]byte(")\n"))
}
