// Copyright 2016 Landoop LTD
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"fmt"
	"io"
	"os"
)

var (
	files = map[string]string{
		"mainTemplate": "template.html",
	}
	outFile = "template_autogenerated.go"
)

// Read all files and save them as strings literals in wordlists.go
func main() {
	out, err := os.Create(outFile)
	if err != nil {
		fmt.Println(err)
	}
	defer out.Close()

	out.Write([]byte("package main\n\nconst (\n"))

	for k, v := range files {
		out.Write([]byte(k + " = `"))
		f, err := os.Open(v)
		if err != nil {
			fmt.Println(err)
		}
		defer f.Close()
		io.Copy(out, f)
		out.Write([]byte("`\n"))
	}
	out.Write([]byte(")\n"))
}
